"""Photos of places: finding freely licensed candidates, adding the chosen ones as drafts, reviewing them,
and hosting our own resized copies.

Attribution is never typed by hand. A researcher picks a candidate by its key, and the author, license,
and source come from the source's own metadata, as coordinates come from Wikidata and OpenStreetMap.

Sources, in order: the place's Wikidata image (P18) and Commons category (P373), Commons files taken
nearby (which include millions of Geograph photos at full size, and scans from archives), Geograph in
Britain and Ireland, and Flickr, whose "no known copyright restrictions" photos come from archives and
libraries. Flickr needs a free API key (PSST_FLICKR_KEY in ~/.config/psst/env) and is skipped without one.
Only free licenses are accepted: public domain, CC0, CC BY, and CC BY-SA. Wikipedia's non-free files
aren't on Commons, and files Commons marks as AI-generated are refused.
"""

from __future__ import annotations

import hashlib
import html
import io
import json
import re
import subprocess
import time
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import asdict, dataclass
from pathlib import Path

from PIL import Image, ImageOps

from . import db, ids, net, rules

# Wikimedia asks for a descriptive User-Agent with a way to reach the operator; a URL is enough.
USER_AGENT = "PsstContent/1.0 (https://psst.zigao.wang/)"
COMMONS_API = "https://commons.wikimedia.org/w/api.php"
REMOTE_DIR = "/www/wwwroot/psst/public/images"
# Commons serves thumbnails in fixed sizes (500, 960, 1920, 3840 px); other widths are rounded up.
FULL_EDGE = 1920
PREVIEW_EDGE = 500
THUMB_EDGE = 640
JPEG_QUALITY = 82
MAX_CANDIDATES = 24
OWNER_LICENSE = "All rights reserved"

FREE_LICENSE = re.compile(r"^(public domain|pd\b|pdm|cc0|cc[ -]by(?:[ -]sa)?[ -]?\d(?:\.\d)?)", re.I)
NOT_FREE = re.compile(r"\b(nc|nd|non[- ]?commercial|no[- ]?deriv|fair use|non[- ]?free|all rights reserved)\b", re.I)


@dataclass
class Candidate:
    key: str            # "commons:File:Big Ben.jpg", "geograph:123456", "flickr:5432"
    source: str         # commons, geograph, flickr, archive
    source_ref: str
    source_url: str
    image_url: str      # a large rendition to download
    preview_url: str    # a small one to look at
    title: str
    author: str
    author_url: str | None
    license: str
    license_url: str | None
    width: int
    height: int
    year: int | None
    found_via: str
    description: str = ""


def is_free(license_name: str) -> bool:
    return bool(FREE_LICENSE.match(license_name.strip())) and not NOT_FREE.search(license_name)


def _get_json(url: str) -> dict:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    for attempt in range(4):
        try:
            with urllib.request.urlopen(request, timeout=60) as response:
                return json.loads(response.read())
        except urllib.error.HTTPError as exc:
            if exc.code not in (429, 503) or attempt == 3:
                raise
        except (urllib.error.URLError, TimeoutError):
            if attempt == 3:
                raise
        time.sleep(3 * (attempt + 1))
    return {}


def _commons(params: dict) -> dict:
    # maxlag asks the API to refuse us, rather than slow down others, when its servers are busy.
    query = urllib.parse.urlencode({"format": "json", "formatversion": 2, "maxlag": 5, **params})
    return _get_json(f"{COMMONS_API}?{query}")


def _text(value) -> str:
    """Commons metadata is HTML (and sometimes a number); credit lines need plain text."""
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", " ", str(value or "")))).strip()


def _first_link(value) -> str | None:
    match = re.search(r'href="((?:https?:)?//[^"]+)"', str(value or ""))
    if not match:
        return None
    url = match.group(1)
    return "https:" + url if url.startswith("//") else url.replace("http://", "https://", 1)


AI_MADE = re.compile(r"AI-generated|Generated by AI|Midjourney|Stable Diffusion|DALL-E|AI upscaled", re.I)


def _year(value: str | None) -> int | None:
    match = re.search(r"\b(1[89]\d\d|20\d\d)\b", _text(value))
    return int(match.group(1)) if match else None


def commons_files(titles: list[str], found_via: str) -> list[Candidate]:
    """Candidates for Commons files, with their license and author from Commons' own metadata."""
    found: list[Candidate] = []
    for start in range(0, len(titles), 20):
        batch = titles[start:start + 20]
        payload = _commons({"action": "query", "prop": "imageinfo", "titles": "|".join(batch),
                            "iiprop": "url|size|mime|extmetadata", "iiurlwidth": FULL_EDGE})
        for page in payload.get("query", {}).get("pages", []):
            info = (page.get("imageinfo") or [{}])[0]
            if not info or info.get("mime") not in ("image/jpeg", "image/png", "image/webp", "image/tiff"):
                continue
            meta = {k: v.get("value") for k, v in (info.get("extmetadata") or {}).items()}
            license_name = _text(meta.get("LicenseShortName"))
            if not license_name or not is_free(license_name) or meta.get("NonFree"):
                continue
            if AI_MADE.search(_text(meta.get("Categories"))):
                continue
            # A Commons user name reads better without its namespace, as Commons' own credit shows it.
            author = re.sub(r"^User:", "", _text(meta.get("Artist")) or _text(meta.get("Credit")))
            if not author or info.get("width", 0) < 800:
                continue
            title = page["title"]
            year = _year(meta.get("DateTimeOriginal")) or _year(meta.get("DateTime"))
            image_url = info.get("thumburl") or info["url"]
            # Works for every file, including ones too small to have a thumbnail at the full size.
            preview = (f"https://commons.wikimedia.org/wiki/Special:FilePath/"
                       f"{urllib.parse.quote(title.removeprefix('File:'))}?width={PREVIEW_EDGE}")
            found.append(Candidate(
                key=f"commons:{title}", source="commons", source_ref=title,
                source_url=info.get("descriptionurl") or f"https://commons.wikimedia.org/wiki/{urllib.parse.quote(title)}",
                image_url=image_url, preview_url=preview, title=title.removeprefix("File:"),
                author=author[:200], author_url=_first_link(meta.get("Artist")), license=license_name,
                license_url=_text(meta.get("LicenseUrl")) or None, width=info["width"], height=info["height"],
                year=year, found_via=found_via, description=_text(meta.get("ImageDescription"))[:400]))
        time.sleep(0.5)
    return found


def commons_for_place(qid: str | None, lat: float, lon: float, radius: int = 60) -> list[Candidate]:
    titles: dict[str, str] = {}
    if qid:
        claims = net.wikidata_entities([qid], props="claims").get(qid, {}).get("claims", {})
        for claim in claims.get("P18", []):
            value = claim.get("mainsnak", {}).get("datavalue", {}).get("value")
            if value:
                titles.setdefault(f"File:{value}", "Wikidata image (P18)")
        for claim in claims.get("P373", [])[:1]:
            category = claim.get("mainsnak", {}).get("datavalue", {}).get("value")
            if category:
                members = _commons({"action": "query", "list": "categorymembers", "cmtype": "file",
                                    "cmtitle": f"Category:{category}", "cmlimit": 30})
                for member in members.get("query", {}).get("categorymembers", []):
                    titles.setdefault(member["title"], f"Commons category {category}")
    nearby = _commons({"action": "query", "list": "geosearch", "gsnamespace": 6, "gscoord": f"{lat}|{lon}",
                       "gsradius": radius, "gslimit": 30})
    for page in nearby.get("query", {}).get("geosearch", []):
        titles.setdefault(page["title"], f"taken within {radius} m")
    found: list[Candidate] = []
    for via in dict.fromkeys(titles.values()):
        found += commons_files([t for t, v in titles.items() if v == via], via)
    return found


def geograph_near(lat: float, lon: float) -> list[Candidate]:
    """Geograph Britain and Ireland, where every photo is CC BY-SA 2.0. Its standard size is 640 px; many
    Geograph photos are also on Commons at full size, which the Commons search finds first."""
    query = urllib.parse.urlencode({"location": f"{lat},{lon}", "distance": 0.1, "format": "JSON", "perpage": 20})
    try:
        payload = _get_json(f"https://api.geograph.org.uk/syndicator.php?{query}")
    except (urllib.error.URLError, json.JSONDecodeError):
        return []
    found = []
    for item in payload.get("items", []):
        photo_id, thumb = str(item.get("guid", "")), item.get("thumb", "")
        if not photo_id.isdigit() or "_120x120" not in thumb or "by-sa/2.0" not in item.get("licence", ""):
            continue
        image = re.sub(r"^https://s\d\.", "https://s0.", thumb.replace("_120x120", ""))
        found.append(Candidate(
            key=f"geograph:{photo_id}", source="geograph", source_ref=photo_id,
            source_url=f"https://www.geograph.org.uk/photo/{photo_id}", image_url=image, preview_url=image,
            title=item.get("title", ""), author=item.get("author", ""),
            author_url=(item.get("source") or "").replace("http://", "https://", 1) or None,
            license="CC BY-SA 2.0", license_url="https://creativecommons.org/licenses/by-sa/2.0/",
            width=640, height=0, year=_year(item.get("imageTaken")), found_via="Geograph, taken within 100 m"))
    return found


FLICKR_LICENSES = {  # Flickr license ids that are free: CC BY, CC BY-SA, no known restrictions, CC0, PDM.
    "4": ("CC BY 2.0", "https://creativecommons.org/licenses/by/2.0/"),
    "5": ("CC BY-SA 2.0", "https://creativecommons.org/licenses/by-sa/2.0/"),
    "7": ("Public domain (no known copyright restrictions)", "https://www.flickr.com/commons/usage/"),
    "9": ("CC0 1.0", "https://creativecommons.org/publicdomain/zero/1.0/"),
    "10": ("Public domain mark 1.0", "https://creativecommons.org/publicdomain/mark/1.0/"),
    "11": ("CC BY 4.0", "https://creativecommons.org/licenses/by/4.0/"),
    "12": ("CC BY-SA 4.0", "https://creativecommons.org/licenses/by-sa/4.0/"),
}


def flickr_near(lat: float, lon: float, key: str | None) -> list[Candidate]:
    if not key:
        return []
    query = urllib.parse.urlencode({
        "method": "flickr.photos.search", "api_key": key, "lat": lat, "lon": lon, "radius": 0.1,
        "license": ",".join(FLICKR_LICENSES), "extras": "owner_name,license,url_l,url_z,date_taken,o_dims",
        "per_page": 20, "format": "json", "nojsoncallback": 1, "content_types": 0})
    try:
        payload = _get_json(f"https://api.flickr.com/services/rest/?{query}")
    except (urllib.error.URLError, json.JSONDecodeError):
        return []
    found = []
    for photo in payload.get("photos", {}).get("photo", []):
        if photo.get("license") not in FLICKR_LICENSES or not photo.get("url_l"):
            continue
        name, url = FLICKR_LICENSES[photo["license"]]
        archive = photo["license"] == "7"  # Flickr Commons: archives and libraries sharing their collections
        found.append(Candidate(
            key=f"flickr:{photo['id']}", source="archive" if archive else "flickr", source_ref=photo["id"],
            source_url=f"https://www.flickr.com/photos/{photo['owner']}/{photo['id']}", image_url=photo["url_l"],
            preview_url=photo.get("url_z", photo["url_l"]), title=photo.get("title", ""),
            author=photo.get("ownername") or photo["owner"], author_url=f"https://www.flickr.com/people/{photo['owner']}",
            license=name, license_url=url, width=int(photo.get("width_l", 0)), height=int(photo.get("height_l", 0)),
            year=None if archive else _year(photo.get("datetaken")),
            found_via="Flickr Commons (an archive's collection)" if archive else "Flickr, taken within 100 m"))
    return found


def find(place: dict, settings: dict) -> list[Candidate]:
    candidates = commons_for_place(place["wikidata_id"], place["lat"], place["lon"])
    if place["country_code"] in ("GB", "IE", "IM", "JE", "GG"):
        candidates += geograph_near(place["lat"], place["lon"])
    candidates += flickr_near(place["lat"], place["lon"], settings.get("PSST_FLICKR_KEY"))
    unique: dict[str, Candidate] = {}
    for c in candidates:
        unique.setdefault(c.key, c)
    # In source order (the Wikidata image first, then its Commons category, then nearby photos), capped so a
    # researcher can look at every one.
    return list(unique.values())[:MAX_CANDIDATES]


def fetch_bytes(url: str) -> bytes:
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    for attempt in range(4):
        try:
            with urllib.request.urlopen(request, timeout=90) as response:
                return response.read(40_000_000)
        except urllib.error.HTTPError as exc:
            if exc.code not in (429, 503) or attempt == 3:
                raise
        time.sleep(3 * (attempt + 1))
    raise RuntimeError(f"couldn't download {url}")


def write_candidates(place: dict, candidates: list[Candidate], directory: Path) -> Path:
    """Save the candidates and a small preview of each, so the researcher can look before choosing."""
    directory.mkdir(parents=True, exist_ok=True)
    lines = [f"# Photos for {place['name']} ({place['id']})", "",
             "Look at each preview (open the file) before choosing. Pick by key; the credit comes from the source.", ""]
    for n, c in enumerate(candidates, 1):
        preview = directory / f"{n:02d}.jpg"
        try:
            preview.write_bytes(fetch_bytes(c.preview_url))
        except (urllib.error.URLError, RuntimeError):
            preview = None
        lines.append(f"{n:02d}. key: {c.key}")
        lines.append(f"    {c.title} | {c.author} | {c.license} | {c.year or 'year unknown'} | {c.width}x{c.height} | "
                     f"{c.found_via}")
        lines.append(f"    preview: {preview or 'unavailable'}  source: {c.source_url}")
    (directory / "candidates.json").write_text(json.dumps([asdict(c) for c in candidates], ensure_ascii=False, indent=1))
    (directory / "candidates.md").write_text("\n".join(lines) + "\n")
    return directory / "candidates.md"


# Our copies ---------------------------------------------------------------------------------------------

@dataclass
class Rendition:
    name: str
    data: bytes
    width: int
    height: int


def renditions(data: bytes) -> tuple[Rendition, Rendition]:
    """A full-size copy and a thumbnail, as progressive JPEGs with no metadata (no camera or location data),
    named by their hashes so a published file never changes."""
    image = ImageOps.exif_transpose(Image.open(io.BytesIO(data))).convert("RGB")
    out = []
    for edge in (FULL_EDGE, THUMB_EDGE):
        copy = image.copy()
        copy.thumbnail((edge, edge), Image.LANCZOS)
        buffer = io.BytesIO()
        copy.save(buffer, "JPEG", quality=JPEG_QUALITY, optimize=True, progressive=True)
        body = buffer.getvalue()
        out.append(Rendition(f"{hashlib.sha256(body).hexdigest()[:24]}.jpg", body, copy.width, copy.height))
    return out[0], out[1]


def upload(host: str, files: list[Rendition]) -> None:
    import tempfile
    with tempfile.TemporaryDirectory() as scratch:
        for f in files:
            (Path(scratch) / f.name).write_bytes(f.data)
        subprocess.run(["ssh", host, f"mkdir -p {REMOTE_DIR}"], check=True)
        subprocess.run(["rsync", "-rt", "--ignore-existing", "--no-owner", "--no-group", f"{scratch}/",
                        f"{host}:{REMOTE_DIR}/"], check=True)
    # Readable by the web server whatever the local permissions were. (macOS's rsync has no --chmod.)
    subprocess.run(["ssh", host, f"chmod 755 {REMOTE_DIR} && chmod 644 " + " ".join(f"{REMOTE_DIR}/{f.name}" for f in files)],
                   check=True)


# Drafts -------------------------------------------------------------------------------------------------

MAX_PER_PLACE = 6
LAZY_ALT = re.compile(r"^(an? )?(image|photo|photograph|picture|view) (of|showing)\b", re.I)


def load_candidates(work: Path, place_id: str) -> dict[str, Candidate]:
    path = work / place_id / "candidates.json"
    if not path.exists():
        return {}
    return {c["key"]: Candidate(**c) for c in json.loads(path.read_text())}


def check_alt(where: str, alt: str, report: rules.Report) -> None:
    if not 10 <= len(alt or "") <= 300:
        report.error(where, "alt text must be 10 to 300 characters")
        return
    if LAZY_ALT.search(alt):
        report.error(where, "alt text starts with 'Image of' or similar; VoiceOver already says it's an image")
    rules.check_prose(report, where, "alt", alt)


def check_details(where: str, entry: dict, report: rules.Report) -> None:
    focus = entry.get("focus", [0.5, 0.5])
    if not (isinstance(focus, list) and len(focus) == 2 and all(isinstance(v, (int, float)) and 0 <= v <= 1 for v in focus)):
        report.error(where, "focus must be [x, y] with each between 0 and 1 (0,0 is the top left)")
    kind = entry.get("kind", "photo")
    if kind not in ("photo", "historic"):
        report.error(where, "kind must be photo or historic")
    year = entry.get("year")
    if year is not None and not (isinstance(year, int) and 1820 <= year <= 2100):
        report.error(where, "year must be a whole year between 1820 and 2100")
    if kind == "historic" and year is None:
        report.error(where, "a historic photo needs the year it was taken (circa is fine; say so in the alt text)")


def check_draft(conn, entries: list[dict], work: Path) -> rules.Report:
    report = rules.Report()
    per_place: dict[str, int] = {}
    for n, entry in enumerate(entries):
        where = f"[{n}] {entry.get('place')}"
        place = conn.execute("SELECT id FROM places WHERE id = %s AND state = 'active'", (entry.get("place"),)).fetchone()
        if not place:
            report.error(where, "no active place with this id")
            continue
        candidate = load_candidates(work, entry["place"]).get(entry.get("key", ""))
        if not candidate:
            report.error(where, f"{entry.get('key')!r} isn't one of the candidates found for this place "
                                "(run psst images find for it, and copy the key exactly)")
            continue
        if entry.get("kind") == "historic" and entry.get("year") is None and candidate.year:
            entry["year"] = candidate.year  # the date Commons records for it
        check_alt(where, entry.get("alt", ""), report)
        check_details(where, entry, report)
        taken = conn.execute("SELECT state FROM images WHERE place_id = %s AND source = %s AND source_ref = %s",
                             (entry["place"], candidate.source, candidate.source_ref)).fetchone()
        if taken:
            report.error(where, f"this photo is already stored for the place ({taken['state']})")
        existing = conn.execute("SELECT count(*) AS n FROM images WHERE place_id = %s AND state <> 'retired'",
                                (entry["place"],)).fetchone()["n"]
        per_place[entry["place"]] = per_place.get(entry["place"], existing) + 1
        if per_place[entry["place"]] > MAX_PER_PLACE:
            report.error(where, f"more than {MAX_PER_PLACE} photos for one place; choose the best")
    return report


def add(conn, host: str, run: dict, place_id: str, candidate: Candidate, alt: str, focus: list[float],
        kind: str, year: int | None) -> str:
    full, thumb = renditions(fetch_bytes(candidate.image_url))
    upload(host, [full, thumb])
    return _insert(conn, run, place_id, candidate.source, candidate.source_ref, candidate.source_url,
                   candidate.title, candidate.author, candidate.author_url, candidate.license, candidate.license_url,
                   alt, focus, kind, year, full, thumb)


def add_owner_photo(conn, host: str, run: dict, place_id: str, path: Path, owner: str, owner_url: str, alt: str,
                    focus: list[float], kind: str, year: int | None) -> str:
    data = path.read_bytes()
    full, thumb = renditions(data)
    upload(host, [full, thumb])
    return _insert(conn, run, place_id, "owner", hashlib.sha256(data).hexdigest()[:24], owner_url, None, owner,
                   owner_url, OWNER_LICENSE, None, alt, focus, kind, year, full, thumb)


def _insert(conn, run, place_id, source, source_ref, source_url, title, author, author_url, license_name, license_url,
            alt, focus, kind, year, full, thumb) -> str:
    image_id = ids.new("im")
    position = conn.execute("SELECT coalesce(max(position) + 1, 0) AS n FROM images WHERE place_id = %s "
                            "AND state <> 'retired'", (place_id,)).fetchone()["n"]
    conn.execute("""
        INSERT INTO images (id, place_id, position, kind, year, source, source_ref, source_url, title, author, author_url,
                            license, license_url, alt_text, focus_x, focus_y, full_file, full_width, full_height,
                            thumb_file, thumb_width, thumb_height, added_by, added_run)
        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
                 (image_id, place_id, position, kind, year, source, source_ref, source_url, title, author, author_url,
                  license_name, license_url, alt, focus[0], focus[1], full.name, full.width, full.height,
                  thumb.name, thumb.width, thumb.height, run["model"] or run["operator"], run["id"]))
    return image_id


def places_needing_images(conn, city: str | None, place: str | None, limit: int) -> list[dict]:
    """Places with published stories and no photo yet, the ones with the most stories first."""
    return conn.execute("""
        SELECT p.id, n.name, p.wikidata_id, ST_Y(p.geom) AS lat, ST_X(p.geom) AS lon, p.country_code
        FROM places p JOIN place_names n ON n.place_id = p.id AND n.role = 'display'
        LEFT JOIN admin_areas ci ON ci.id = p.city_id
        WHERE p.state = 'active' AND (%(place)s::text IS NULL OR p.id = %(place)s)
          AND (%(city)s::text IS NULL OR ci.name = %(city)s)
          AND (%(place)s::text IS NOT NULL OR (
               EXISTS (SELECT 1 FROM facts f WHERE f.place_id = p.id AND f.state = 'published')
               AND NOT EXISTS (SELECT 1 FROM images i WHERE i.place_id = p.id)))
        ORDER BY (SELECT count(*) FROM facts f WHERE f.place_id = p.id AND f.state = 'published') DESC, p.id
        LIMIT %(limit)s""", {"place": place, "city": city, "limit": limit}).fetchall()


# Review -------------------------------------------------------------------------------------------------

def review_queue(conn, limit: int) -> list[dict]:
    """Flagged published images first, then drafts, with what a reviewer needs to judge each one."""
    return conn.execute("""
        SELECT i.id, i.place_id, n.name AS place, i.state, i.needs_review, i.kind, i.year, i.source, i.source_url,
               i.title, i.author, i.license, i.alt_text AS alt, ARRAY[i.focus_x, i.focus_y] AS focus, i.position,
               p.kind AS place_kind, ST_Y(p.geom) AS lat, ST_X(p.geom) AS lon, p.wikidata_id,
               (SELECT array_agg(f.headline ORDER BY f.position) FROM facts f
                WHERE f.place_id = i.place_id AND f.state IN ('published', 'reviewed')) AS stories
        FROM images i JOIN places p ON p.id = i.place_id
        JOIN place_names n ON n.place_id = p.id AND n.role = 'display'
        WHERE i.state = 'draft' OR (i.needs_review AND i.state <> 'retired')
        ORDER BY i.needs_review DESC, i.place_id, i.position LIMIT %s""", (limit,)).fetchall()


def show(conn, base_url: str, run: dict, image_id: str, work: Path) -> Path:
    """Download our hosted copy (what readers will see) for a reviewer to look at, and record that they did."""
    row = conn.execute("SELECT full_file FROM images WHERE id = %s", (image_id,)).fetchone()
    if not row:
        raise RuntimeError(f"No image {image_id}")
    work.mkdir(parents=True, exist_ok=True)
    path = work / f"{image_id}.jpg"
    path.write_bytes(fetch_bytes(f"{base_url}/images/{row['full_file']}"))
    conn.execute("INSERT INTO image_views (run_id, image_id) VALUES (%s, %s) ON CONFLICT DO NOTHING",
                 (run["id"], image_id))
    return path


def as_mapping(decisions) -> dict:
    """Photo decisions as {id: decision}; the list form ([{"image": id, ...}]) used by facts and guides works too."""
    if isinstance(decisions, list):
        return {d.get("image"): d for d in decisions if isinstance(d, dict)}
    if isinstance(decisions, dict):
        return decisions
    raise ValueError("decisions must be a list of decisions or an object keyed by photo id")


def check_decisions(conn, decisions, run: dict) -> rules.Report:
    report = rules.Report()
    decisions = as_mapping(decisions)
    for image_id, d in decisions.items():
        row = conn.execute("SELECT state, kind, year, needs_review, added_run FROM images WHERE id = %s FOR UPDATE",
                           (image_id,)).fetchone()
        if not row:
            report.error(image_id, "no such image")
            continue
        if row["added_run"] == run["id"]:
            report.error(image_id, "a run can't review the photos it added")
        if row["state"] == "retired":
            report.error(image_id, "already retired")
        decision = d.get("decision")
        if decision not in ("approve", "edit", "reject"):
            report.error(image_id, "decision must be approve, edit, or reject")
            continue
        if not (d.get("notes") or "").strip():
            report.error(image_id, "notes are required: what the photo shows, and how you know it's this place")
        viewed = conn.execute("SELECT 1 FROM image_views WHERE run_id = %s AND image_id = %s",
                              (run["id"], image_id)).fetchone()
        if decision != "reject" and not viewed:
            report.error(image_id, f"this run never looked at the photo; run psst images show {image_id} first")
        if decision == "edit":
            if "alt" in d:
                check_alt(image_id, d["alt"], report)
            merged = {"focus": d.get("focus", [0.5, 0.5]), "kind": d.get("kind", row["kind"]),
                      "year": d.get("year", row["year"])}
            check_details(image_id, merged, report)
            if "position" in d and not (isinstance(d["position"], int) and d["position"] >= 0):
                report.error(image_id, "position must be a whole number, 0 first")
    return report


def apply_decisions(conn, decisions, run: dict) -> dict[str, int]:
    counts = {"approve": 0, "edit": 0, "reject": 0}
    for image_id, d in as_mapping(decisions).items():
        decision = d["decision"]
        counts[decision] += 1
        if decision == "reject":
            conn.execute("""UPDATE images SET state = 'retired', retired_at = now(), retire_reason = %s,
                                reviewed_at = now(), reviewed_by = %s, review_run = %s, review_notes = %s,
                                needs_review = false WHERE id = %s""",
                         (f"Rejected in review: {d['notes']}"[:500], run["model"] or run["operator"], run["id"],
                          d["notes"], image_id))
            continue
        updates = {"alt_text": d.get("alt"), "kind": d.get("kind"), "year": d.get("year"),
                   "position": d.get("position")}
        if "focus" in d:
            updates["focus_x"], updates["focus_y"] = d["focus"]
        sets = [f"{k} = %s" for k, v in updates.items() if v is not None]
        values = [v for v in updates.values() if v is not None]
        conn.execute(f"""UPDATE images SET {', '.join(sets + [''])} reviewed_at = now(), reviewed_by = %s,
                             review_run = %s, review_notes = %s, needs_review = false,
                             state = CASE WHEN state = 'draft' THEN 'reviewed' ELSE state END
                         WHERE id = %s""",
                     (*values, run["model"] or run["operator"], run["id"], d["notes"], image_id))
    return counts
